language: android
jdk: oraclejdk8

android:
 components:
 - tools
 - platform-tools
 - build-tools-27.0.3
 - android-27
 - extra-google-m2repository
 - extra-android-m2repository

before_script:
- chmod 755 ./gradlew
- chmod 755 ./build-apk.sh

script:
- ./gradlew testDebugUnittest
- ./build-apk.sh

deploy:
  provider: releases
api_key:
  secure:tNIvNNLbdPUUwd1ETZHewIrTwyaBY5yN+o4zEVHa46ZeTUEt3Bgi6F26L3Psfw8TOLWmvwoyLhMUfQFpL32FpPNJYPFmkZ7YLwzx1ZICYT0O6Ee1R6wA5NVAD434Xy/nGcGYmnuhcDtKKAjVR9IHg0CBfwCJx5QUwf53JIcIaPnUuuRd+oijYxHm3zbPi+bOhecQy2jMyfThZJolsyYGRk7DWznCn+7XeLBHZ5Wc2EiJz31fp0V9piCIVNs2m1XENf7JOGG/BNmnAAXuZRVzjYJww6AN/n9Hri+PCxO4kZLq5/dmaPKcKzwA8Ls6XVMTceKv+BKqW08EtNORZX1IAJuuYVKIeiKXGEschH0+sn2tRbPnJmOOopXL6mqrYKkCBN0HlmunMbUwPV1t6CqLljiUl1H571c6f6yJ79JLydPga+awqVJonsg7Rc6H1kE5u+JvCIE9YkvRP6K+Dev0N+FLRS/6fbCynxA+6bAOEkYCCVPI3/3AqIExhfTP8FN5gTV5B6l15tKFz/mrRXDmgyieDKyAJegjn28Ywc8nBJIDJMkHOARA8ydp46EsWWiNAV1DqnKzPqq/icB+DIkhQHddYCeeHQ8u7HsXQvJUjJTbaTmkjn/bYbfXMxqglpEYKnmFSlUdR5mfEUE05WL+eQlj1wgQtLpbBVtHQonzXHg=

file: "./build/apk/juxebox.apk"
file_glob: true
skip_cleannup : true
on:
  repo: JulienHivert/ptut_Ol-d_Tam
  branch: master
