language: android

jdk: oraclejdk8

android:
 components:
 - tools
 - platform-tools
 - build-tools-27.0.3
 - android-27
 - extra-google-m2repository
 - extra-android-m2repository

before_script:
- chmod 755 ./gradlew
- chmod 755 ./build-apk.sh

script:
- ./gradlew testDebugUnittest
- ./build-apk.sh

deploy:
  provider: releases
  
  api_key:
     secure: "f52P4PFMgNwA+6RjhpWLE0nxF92k7HZn5lp6U5yrnxBUs964gqdBb6KIzStc5kyiWApPpGkHnR93uyAEOPbDrdasqDS56R7zr88gykcz6mCa6w9vHWIXBmRk2dMShp9k+U9j65yPtyZFyr1c6/sY3MNdATRuO1Wt3/xWoZwII4w2ZojMaxnoBuqgxRlP6LJHSfhQX2nx+KLD/4CbCaS8Bhn2xFtL9Y/jAV9HdvfkHKb9ERALTEsJoC32Oklq7vzIb7L7Iny3t95AcsIPVVAzQP6F4jxk186LEskCgM5rU9S2/3Zn0QCs2Cgf19JS9GJg0a3UmeEq9l2wPZfZdBUXh0zVqr2+rKyMzUq8bFQXNprNwcZGONMskI1pvYkmCMeeJ2lBX2Hkvf55gijQB0yGWESLiOMWT3uIRlZWaVwr/e5+S73TKxzIFWZmDCgHadkFv2A/NXbibFJ5OXUevn+VFmeiwY+UV/z+YYGpJL7tSErU87HqtzCYrXwNoyS1GM6xwdZY8FVKUHpModAAVlaytO2lZexoxUPPzbiSizmBw/tbWlMgB8o6rqthBUDr4s+I+4EbTzuVtzlJ31UJG56yLxNCyoOTXc4XeXPEXv9ESdkpWXmmO+lSWhgsPHkTGWG9JteiUlIjiiGVstoSqn7jzDBxUcDoBxRwC/eMS5JrYTU="
    
  file: "./build/apk/juxebox.apk"
  file_glob: true
  skip_cleannup : true
  on:
    repo: JulienHivert/ptut_Ol-d_Tam
    branch: master
